jobs:
  - job: DockerizeAndPush
    displayName: "Docker Build & Push"
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      IMAGE_NAME: 'api-rest-springboot'
      DOCKERHUB_REPO: 'jessi93/api-rest-springboot'

    steps:
      - task: Docker@2
        displayName: 'Build & Push'
        inputs:
          containerRegistry: 'dockerHub'
          repository: '$(DOCKERHUB_REPO)'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            latest
            $(Build.BuildId)
