jobs:
  - job: BuildAndAnalyze
    displayName: " Build + Análisis Sonar"
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      IMAGE_NAME: 'api-rest-springboot'
      DOCKERHUB_REPO: 'jessi93/api-rest-springboot'

    steps:
      - task: JavaToolInstaller@1
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64' 
          jdkSourceOption: 'PreInstalled'

      - task: SonarQubePrepare@7
        inputs:
          SonarQube: 'sonarq_Servcice'
          scannerMode: 'other'

      - task: Cache@2
        inputs:
          key: 'gradle | "$(Agent.OS)" | build.gradle'
          path: ~/.gradle
          restoreKeys: |
            gradle | "$(Agent.OS)"

      - script: |
          chmod +x ./gradlew
          ./gradlew clean build test
        displayName: 'Compilar y probar con Gradle'

      - task: SonarQubeAnalyze@7
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'

     
      - task: SonarQubePublish@7
        inputs:
          pollingTimeoutSec: '300'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'build/libs'
          ArtifactName: 'drop'  # nombre del artefacto
          publishLocation: 'pipeline'

